apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  type: Opaque
data:
  cacert.pem |
     base-64-encoded value of a PEM certificate
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: my-app-image
    volumeMounts:
      - name: certificate-file
        mountPath: /etc/secret
  volumes:
  - name: certificate-file
    configMap:
      name: my-secret


# The inconvenience with this way of creating a secret for a file is that you will have to base64 encode the file contents and then paste it into the data section.
# So an easier alternative way to create secrets from a file is with kubectl command.

#   kubectl create secret generic my-secret --from-file=./cacert.pem
